bookshelf/blog/urls.py
from django.urls import path

from . import views

from .feeds import LatestPostsFeed


app_name = "blog"

urlpatterns = [
    path("", views.index, name="post_list"),
    path(
        "tag/<slug:tag_slug>/",
        views.index,
        name="post_index_by_tag",
    ),
    path(
        "<int:pk>/",
        views.post_detail,
        name="post_detail",
    ),
    path(
        "<int:pk>/comment/",
        views.post_comment_create,
        name="post_comment",
    ),
    path(
        "<int:pk>/share/",
        views.PostEmailView.as_view(),
        name="post_share",
    ),
    path(
        "create/",
        views.CreatePostView.as_view(),
        name="post_create",
    ),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

bookshelf/bookshelf/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from django.conf import settings
from django.conf.urls.static import static


from django.urls import path, include

from django.views.generic import TemplateView

from blog.sitemaps import PostSitemap, TagSitemap

sitemaps = {
    "posts": PostSitemap,
    "tags": TagSitemap,
}
urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="index.html",
        ),
        name="index",
    ),
    path("", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path(
        "blog/",
        include(
            "blog.urls",
            namespace="blog",
        ),
    ),
    path(
        "account/",
        include(
            "account.urls",
            namespace="account",
        ),
    ),
    path(
        "books/",
        include(
            "book.urls",
            namespace="book",
        ),
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "social-auth/",
        include(
            "social_django.urls",
            namespace="social",
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

bookshelf/blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(
                status=Post.Status.PUBLISHED,
            )
        )


# Create your models here.
class Post(models.Model):
    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        unique_for_date="publish",
    )
    tags = TaggableManager()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="user_posts",
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT,
    )
    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.pk,
            ],
        )

    def __str__(self):
        return self.title


class Comment(models.Model):
    class Meta:
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
        ]

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse(
            "blog:post_comment",
            args=[
                self.pk,
            ],
        )

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

bookshelf/blog/forms.py
from django import forms

from .models import Post, Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea(),
    )


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "title",
            "slug",
            "body",
            "author",
            "status",
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField()

bookshelf/blog/views.py
from audioop import reverse
from re import search

from django.contrib.postgres.search import (
    SearchVector,
    SearchQuery,
    SearchRank,
)

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from django.views.decorators.http import require_POST

from django.db.models import Count

from django.contrib.postgres.search import TrigramSimilarity


from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    FormView,
)

from django.core.mail import send_mail

from taggit.models import Tag

from .models import Post, Comment

from .forms import EmailPostForm, PostForm, CommentForm, SearchForm


# Create your views here.
def index(request, tag_slug=None):
    posts_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(
            Tag,
            slug=tag_slug,
        )
        posts_list = posts_list.filter(tags__in=[tag])

    paginator = Paginator(posts_list, 3)
    page_number = request.GET.get("page", 1)
    try:
        posts = paginator.get_page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        "blog/index.html",
        {
            "posts": posts,
            "tag": tag,
        },
    )


# class PostListView(ListView):
#     model = Post
#     template_name = "blog/index.html"
#     context_object_name = "posts"
#     paginate_by = 5


class CreatePostView(CreateView):
    model = Post
    form_class = PostForm


def post_detail(request, pk: int):
    post = get_object_or_404(
        Post,
        pk=pk,
        status=Post.Status.PUBLISHED,
    )
    # List of active comments for this blog
    comments = post.comments.filter(active=True)

    # Form for users to comment
    form = CommentForm()

    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]

    return render(
        request,
        "blog/post_detail.html",
        {
            "post": post,
            "comments": comments,
            "form": form,
            "similar_posts": similar_posts,
        },
    )


class PostEmailView(FormView):
    template_name = "blog/email_share.html"
    form_class = EmailPostForm
    success_url = "/thanks"

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs.get("pk"))
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (
                f"{cd['name']} ({cd['email']}) " f"recommends you read {post.title}"
            )
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}'s comments: {cd['comments']}"
            )
            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd["to"]],
            )
            sent = True
            return render(
                request,
                self.template_name,
                {
                    "post": post,
                    "form": form,
                    "sent": sent,
                },
            )

    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs.get("pk"))
        sent = False
        return render(
            request,
            self.template_name,
            {
                "post": post,
                "form": self.form_class,
                "sent": sent,
            },
        )


# class CommentCreateView(CreateView):
#     template_name = "blog/post_comment.html"
#     model = Comment
#     form_class = CommentForm


@require_POST
def post_comment_create(request, pk: int):
    post = get_object_or_404(
        Post,
        pk=pk,
        status=Post.Status.PUBLISHED,
    )
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(
        request,
        "blog/post_comment.html",
        context={
            "post": post,
            "form": form,
            "comment": comment,
        },
    )


def post_search(request):
    form = SearchForm(request.GET or None)
    query = request.GET.get("query")
    results = []

    if query:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            # search_vector = SearchVector(
            #     "title",
            #     weight="A",
            # ) + SearchVector(
            #     "body",
            #     weight="B",
            # )
            # search_query = SearchQuery(query)
            # results = (
            #     Post.published.annotate(
            #         search=search_vector,
            #         rank=SearchRank(search_vector, search_query),
            #     )
            #     .filter(rank__gte=0.3)
            #     .order_by("-rank")
            # )

            results = (
                Post.published.annotate(
                    similarity=TrigramSimilarity(
                        "title",
                        query,
                    )
                )
                .filter(similarity__gte=0.1)
                .order_by("-similarity")
            )

    return render(
        request,
        "blog/search.html",
        context={
            "form": form,
            "query": query,
            "results": results,
        },
    )

bookshelf/blog/templates/blog/base.html
{% extends 'base.html' %}

{% block body %}
    <div id="content">
    </div>
{% endblock %}

bookshelf/blog/templates/blog/email_share.html
{% extends 'blog/base.html' %}

{% block title %}
    Share post
{% endblock %}

{% block body %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

bookshelf/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Blog{% endblock %}
{% block body %}
    <div id="sidebar">
        <h2>My blog</h2>
        <p>
            This is my blog.
            I've written {% total_posts %} posts so far.
        </p>
        <p>
            <a href="{% url "blog:post_feed" %}">
                Subscribe to my RSS feed
            </a>
        </p>

        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}
        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>

    </div>
    <a class="btn btn-primary mb-3" href="{% url 'blog:post_create' %}" role="button">
        Create post
    </a>
    {% if tag %}
        <h3>Posts tagged with "{{ tag.name }}"</h3>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_index_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a> {% if not forloop.last %}, {% endif %}
            {% endfor %}    

        <p class="date">
            Published {{ post.publish }}by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}

    {% endfor %}
    {% include "components/pagination.html" with page=posts %}
{% endblock %}

bookshelf/blog/templates/blog/latest_posts.html
<ul>
{% for post in latest_posts %}
<li>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</li>
{% endfor %}
</ul>

bookshelf/blog/templates/blog/post_comment.html
{% extends 'blog/base.html' %}

{% block title %}
Add a comment
{% endblock %}
{% block body %}
    {% if comment %}
       <h2>Your comment has been added.</h2>
       <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "blog/components/comment_form.html" %}
    {% endif %}
{% endblock %}

bookshelf/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block body %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.pk %}">
        Share the post
    </a>
    </p>
    <p>
        <a href="{% url "blog:post_list" %}">
            Back to posts list
        </a>
    </p>
    <h3>Similar posts</h3>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </p>
        {% empty %}
            <p>There are no similar posts.</p>
    {% endfor %}    
    
    {% with comments.count as total_comments %}
        <h4>
        {{ total_comments }} comment{{ total_comments|pluralize }}
        </h4>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
            </p>
            {{ comment.body|truncatewords:10|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments.</p>
    {% endfor %}
    {% include "blog/components/comment_form.html" %}
{% endblock %}

bookshelf/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block title %}
  Create new post
{% endblock %}
{% block body %}
    <form method="post">{% csrf_token %}
        <div>
            {{ form.as_p }}
        </div>
        <button type="submit">Submit</button>
    </form>
{% endblock %}

bookshelf/blog/templates/blog/search.html
cr{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block body %}
    {% if query %}
        <h2>Posts containing "{{ query }}"</h2>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>

        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            <p>{{ post.body|markdown|truncatewords_html:12 }}</p>
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}

        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h2>Search for posts</h2>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}