bookshelf/account/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls.conf import include

from . import views

app_name = "account"


urlpatterns = [
    # path("", include("django.contrib.auth.urls")),
    # login / logout urls
    # path(
    #     "login/",
    #     auth_views.LoginView.as_view(),
    #     name="login",
    # ),
    # path(
    #     "logout/",
    #     auth_views.LogoutView.as_view(next_page="account:login"),
    #     name="logout",
    # ),
    # # change password urls
    # path(
    #     "password-change/",
    #     auth_views.PasswordChangeView.as_view(),
    #     name="password_change",
    # ),
    # path(
    #     "password-change/done/",
    #     auth_views.PasswordChangeDoneView.as_view(),
    #     name="password_change_done",
    # ),
    # # reset password urls
    # path(
    #     "password-reset/",
    #     auth_views.PasswordResetView.as_view(),
    #     name="password_reset",
    # ),
    # path(
    #     "password-reset/done/",
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done",
    # ),
    # path(
    #     "password-reset/<uidb64>/<token>/",
    #     auth_views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm",
    # ),
    # path(
    #     "password-reset/complete/",
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete",
    # ),
    path("", include("django.contrib.auth.urls")),
    path("profile/", views.get_profile, name="profile"),
    path("register/", views.register, name="register"),
    path("edit-profile/", views.edit_profile, name="edit_profile"),
]

bookshelf/blog/urls.py
from django.urls import path

from . import views

from .feeds import LatestPostsFeed


app_name = "blog"

urlpatterns = [
    path("", views.index, name="post_list"),
    path(
        "tag/<slug:tag_slug>/",
        views.index,
        name="post_index_by_tag",
    ),
    path(
        "<int:pk>/",
        views.post_detail,
        name="post_detail",
    ),
    path(
        "<int:pk>/comment/",
        views.post_comment_create,
        name="post_comment",
    ),
    path(
        "<int:pk>/share/",
        views.PostEmailView.as_view(),
        name="post_share",
    ),
    path(
        "create/",
        views.CreatePostView.as_view(),
        name="post_create",
    ),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

bookshelf/book/urls.py
from django.urls import path

from . import views


app_name = "books"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("top-list/", views.BestBooksListView.as_view(), name="top_list"),
]

bookshelf/bookshelf/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from django.conf import settings
from django.conf.urls.static import static


from django.urls import path, include

from django.views.generic import TemplateView

from blog.sitemaps import PostSitemap, TagSitemap

sitemaps = {
    "posts": PostSitemap,
    "tags": TagSitemap,
}
urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="index.html",
        ),
        name="index",
    ),
    path("", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path(
        "blog/",
        include(
            "blog.urls",
            namespace="blog",
        ),
    ),
    path(
        "account/",
        include(
            "account.urls",
            namespace="account",
        ),
    ),
    path(
        "books/",
        include(
            "book.urls",
            namespace="book",
        ),
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "social-auth/",
        include(
            "social_django.urls",
            namespace="social",
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

bookshelf/templates/components/caousel.html
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
      <div class="carousel-item active">
      <img src="https://images.thalia.media/-/BF2000-2000/f36f5f9aba784d53b0aad18ecf31c06d/martin-eden-taschenbuch-jack-london.jpeg" class="d-block w-25" alt="Martin Eden">
      </div>
      <div class="carousel-item">
      <img src="https://cdn.respublica.ru/uploads/00/00/00/61/hs/large_webp_1ed1656c5e905f5e.webp?1517480116" class="d-block w-25" alt="Financier">
      </div>
      <div class="carousel-item">
      <img src="https://ae04.alicdn.com/kf/S0e4f0826591c4960bb8ced8f79336d2c6.jpg" class="d-block w-25" alt="Steven King">
      </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<style>
.carousel-item img {
    width: 100%; /* Задает ширину 100% от родительского элемента */
    height: 400px; /* Устанавливает фиксированную высоту */
    object-fit: contain; /* Сохраняет пропорции изображения и не обрезает его */
}
</style>

bookshelf/templates/components/carousel.html
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="true">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
      <div class="carousel-item active">
      <img src="https://images.thalia.media/-/BF2000-2000/f36f5f9aba784d53b0aad18ecf31c06d/martin-eden-taschenbuch-jack-london.jpeg" class="d-block w-25" alt="Martin Eden">
      </div>
      <div class="carousel-item">
      <img src="https://cdn.respublica.ru/uploads/00/00/00/61/hs/large_webp_1ed1656c5e905f5e.webp?1517480116" class="d-block w-25" alt="Financier">
      </div>
      <div class="carousel-item">
      <img src="https://ae04.alicdn.com/kf/S0e4f0826591c4960bb8ced8f79336d2c6.jpg" class="d-block w-25" alt="Steven King">
      </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<style>
.carousel-item img {
    width: 100%; /* Задает ширину 100% от родительского элемента */
    height: 400px; /* Устанавливает фиксированную высоту */
    object-fit: contain; /* Сохраняет пропорции изображения и не обрезает его */
}
</style>

bookshelf/templates/components/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
        {% if not request.path == '/' %}
      <a class="navbar-brand" href="{% url 'index' %}">Main page</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li {% if section == "profile" %}class="selected nav-item"{% endif %}>
                <a class="nav-link active" href="{% url "account:profile" %}">My profile</a>
          </li>

          <li {% if section == "blog" %}class="selected nav-item"{% endif %}>
                  <a class="nav-link active" href="{% url 'blog:post_list' %}">Blog</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Books
              </a>
              <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'books:index' %}">What others are reading</a></li>
                  <li><a class="dropdown-item" href="#">Recommend a book</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'books:top_list' %}">Weekly top 10</a></li>
              </ul>
          </li>
          {% if request.user.is_authenticated %}
              <li class="nav-item mb-3">
                <form method="post" action="{% url "account:logout" %}">
                    <button type="submit">Logout</button>
                    {% csrf_token %}
                </form>
              </li>
          {% else %}
              <li class="nav-item mb-3">
                  <form method="post" action="{% url "account:login" %}">
                      <button type="submit">Login</button>
                        {% csrf_token %}
                  </form>
              </li>
          {% endif %}
      </ul>
        <form class="d-flex" role="search" method="get" action="{% url 'blog:post_search' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
  </div>
</nav>

bookshelf/templates/components/pagination.html
  <div class="pagination">
        <span class="step-links">
            {% if page.has_previous %}
                <a href="?page={{ page.previous_page_number }}">Previous</a>
            {% endif %}

            <span class="current">
                Page {{ page.number }} from {{ paginator.num_pages }}.
            </span>

            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}">Next</a>
            {% endif %}
        </span>
    </div>